# Generated by Django 4.2.2 on 2023-06-16 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="id_seller",
            new_name="is_seller",
        ),
    ]
