# Generated by Django 4.2.2 on 2023-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="desciption",
            new_name="description",
        ),
    ]
